apiVersion: v2
name: giropops
description: Primeiro chart do Nginx criado no treinamento
type: application
version: 0.3.1
appVersion: "2.0.0"
keywords:
  - nginx
  - primeira_aula
  - webserver
  - giropops
home: https://github.com/badtuxx/DescomplicandoHelm
sources:
  - https://linuxtips.com.br
maintainers:
- name: Jeferson Fernando
  email: jeferson@linuxtips.com.br
- name: xet
  email: xet@streamdaLINUXtips.com
deprecated: false